# Generated by Django 4.2.7 on 2023-12-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userreg',
        ),
    ]
